image: docker:latest

services:
  - docker:dind



before_script:
  # Add Docker-compose to Docker image
  - apk add --no-cache py-pip
  - pip install docker-compose==1.23.2
  - docker info
  - docker-compose --version


stages:
  - test

test:
  stage: test
  script:
    - echo "Starting tests"
    - docker-compose run app sh -c "python manage.py test && flake8"