image: docker:latest

services:
  - docker:dind

before_script:
  # Add Docker-compose to Docker image
  - apk add --no-cache py-pip
  - pip install docker-compose==1.23.2
  - docker info
  - docker-compose --version

stages:
  - test
  - build
  #- deploy

# variables:
#     HEROKU_API_KEY: fffeedc8-716f-44e2-ad2e-d4d6ca09a3e6
#     HEROKU_STAGING_APP: gulshanclub-staging
#     HEROKU_PRODUCTION_APP: gulshanclub
#     POSTGRES_USER: postgres
#     REGISTRY_NAME: registry.gitlab.com/wsit/wearit-frontend
#     CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF


test:
  stage: test
  script:
    - echo "Starting tests"
    - docker-compose run app sh -c "python manage.py test"

build:
  stage: build
  script:
    - echo "Building the app"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE


deploy_staging:
  stage: deploy
  only:
  - staging
  script:
    - echo "Deploying the app"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE registry.heroku.com/$HEROKU_STAGING_APP/web
    - docker-compose run deploy_staging sh -c "python manage.py migrate"
    - docker push registry.heroku.com/$HEROKU_STAGING_APP/web
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_STAGING_APP

deploy_production:
  stage: deploy
  only:
  - production
  script:
    - echo "Deploying the app"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE registry.heroku.com/$HEROKU_PRODUCTION_APP/web
    - docker-compose run deploy_production sh -c "python manage.py migrate"
    - docker push registry.heroku.com/HEROKU_PRODUCTION_APP/web
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app HEROKU_PRODUCTION_APP