# Generated by Django 3.0 on 2021-01-07 10:29
from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password

def add_user(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    User.objects.create(
        email='migrated@jambonsw.com',
        password=make_password('s3cr3tp4ssw0rd!'),
        username='Migrated',
    )


def remove_user(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    User.objects.get(email='migrated@jambonsw.com').delete()


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(add_user),
    ]
