version: '3'



services:
  wearit_app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '9000:9000'
    external_links:
      - mongo
#   mongo:
#     container_name: mongo
#     image: mongo
#     ports:
#       - '27017:27017'
#   redis:
#     image: "redis:latest"
#     ports:
#       - 6379
#     command: ["redis-server", "--bind", "redis", "--port", "6379"]
#     networks:
#       - mynetwork 

# networks:
#   mynetwork:
#     driver: bridge